import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: ["/favicon.ico?v=4"],
		apple: ["/apple-touch-icon.png?v=4"],
		shortcut: ["/apple-touch-icon.png"],
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
